
#

USE_STANDARD_AS_RULE := true

O_TARGET		:= s1c38000.o

obj-y := generic.o irq.o dma.o
obj-m :=
obj-n :=
obj-  :=

export-objs :=	tte301.o

obj-$(CONFIG_S1C38000_TTE301) += tte301.o

include $(TOPDIR)/Rules.make
