#!/bin/sh

#set -x

SA1100=`egrep "CONFIG_SA11.*=y" ../../.config | sed -e '/FREQ/d;/RTC/d;/FIR/d;/VOLT/d;/DMA/d;/USB/d;/REGMON/d'`
BUS=`egrep "^CONFIG_USBD_.*_BUS" ../../.config | sed /GENERIC/d`

case "$BUS" in
CONFIG_USBD_SA1100_BUS*) export BUS=$SA1100 ;;
esac

BUS=`expr $BUS : '\(.*\)=.*'`

echo $BUS

