#!/bin/sh

if [ -z "$1" ]; then
   echo 'Usage:' `basename $0` destination_directory
   exit 1
fi
set -x
DST=$1
SRC=~/work/Drivers/usbd
WD=`dirname ${SRC}`
SD=`basename ${SRC}`
cd ${WD}
#
# Make a directory skeleton
#
find ${SD} -follow -type d -exec mkdir ${DST}/'{}' \;
#
# Make the links
#
find ${SD} -follow -type f -exec ln -s ${WD}/'{}' ${DST}/'{}' \;
